language: generic
sudo: required
dist: trusty

before_install:
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install fp-compiler

script:
  - echo 'Done!'
